<?php

include_once('dlr_info.features.inc');


/**
 * Implementation of hook_context_links_alter().
 * 
 * Have only one context link button appear for dlr group nodes when the info tab is selected: Edit the node.
 * 
 * Have context links for all nodes which have dlr_nodes_context_links set
 */
function dlr_info_context_links_alter(&$links) {
  $path_query = $_GET['q'];
  if (context_get('context', 'dlr_groups_context_links')) {
    $links = array();
    $node = menu_get_object();
    /* @var $active_space spaces_og class */
    $active_space = spaces_get_space();
     $group_node = node_load($active_space->id);
    
    // The context_links button appaear for info page and pages with nod$group_nodee in the url but not node edit
    if($path_query === "info" || ($group_node->nid == $node->nid && strpos($path_query, "node") !== FALSE && strpos($path_query, "edit") === FALSE && strpos($path_query, "grant") === FALSE)) {
      $item = menu_get_item('node/' . $active_space->id . '/edit');
      $node_type = node_get_types('name', $group_node);
      if ($item['access']) {
        $links['admin_groups'] = array('title' => t('@name bearbeiten', array('@name' => $node_type), 'de'), 'href' => $item['href']);
      }
    }
  }
  if (context_get('context', 'dlr_nodes_context_links')) {
    $links = array();
    $node = menu_get_object();
    $item = menu_get_item('node/' . $node->nid . '/edit');
    //Need to set the following context links for the node types mentioned in the context.
    $links['edit_node'] = array('title' => t('@name bearbeiten', array('@name' => node_get_types('name', $node)), 'de'), 'href' => $item['href'], '#weight' => 0);
    
    //setting a grant context link
    if(nodeaccess_access('grant', $node)){
       $item = menu_get_item('node/' . $node->nid . '/grant');
       $links['node_access'] = array('title' => t('Sichtbarkeitseinstellungen', array('@name' => node_get_types('name', $node)), 'de'), 'href' => $item['href'], '#weight' => 2);     
    }
    
    if($node->type == 'book'){
       $item = menu_get_item('node/add/book');
       $links['edit_node']['title'] = t('Seite bearbeiten', NULL,'de');
       $links['add_book'] = array('title' => t('Unterseite hinzfügen', NULL, 'de'), 'href' => $item['href'], '#weight' => 1);     
    }
  }
}

/**
 * Implementation of hook_form_alter().
 */
function dlr_info_form_alter(&$form, $form_state, $form_id) {
 // $form['#action']  = explode('search', $form['#action']); 
  
  switch ($form_id) {
    // This is our form ID.
    case 'atrium_search_form':
      // Print out the $form array to see all the elements we are working with.
      //$output .= dsm($form);
      // Once I know which part of the array I'm after we can change it.
     
      // Change the Username field title to Login ID.
      $form['#action'] = 'search';
      unset($form['#space']);
      break;
  }
}